export interface Track {
  id: number;
  title: string;
  artist: string;
  album: string;
  file: string;
  duration: number;
  artwork?: {
    src: string;
    description: string;
  }[];
}

export const playlist = [
  {
    id: 1,
    title: 'astrobell',
    artist: 'Pine',
    album: '-',
    file: 'Pine - astrobell.mp3',
    duration: 130.63835,
  },
  {
    id: 2,
    title: 'True (shitted by Pine)',
    artist: 'Akira Yamaoka',
    album: '-',
    file: 'Akira Yamaoka - True (shitted by Pine).mp3',
    duration: 124.7608,
  },
  {
    id: 3,
    title: 'Nacistic Cannibal (RMXD byPine)',
    artist: 'Korn, Squirllex',
    album: '-',
    file: 'Korn, Squirllex - Nacistic Cannibal (RMXD byPine).mp3',
    duration: 132.49305,
  },
  {
    id: 4,
    title: '1 smth + of course',
    artist: 'Pine',
    album: '-',
    file: 'Pine - 1 smth + of course.mp3',
    duration: 312.0849,
  },
  {
    id: 5,
    title: '19072011',
    artist: 'Pine',
    album: '-',
    file: 'Pine - 19072011.mp3',
    duration: 155.141225,
  },
  {
    id: 6,
    title: 'A frozen thought',
    artist: 'Pine',
    album: '-',
    file: 'Pine - A frozen thought.mp3',
    duration: 113.214675,
  },
  {
    id: 7,
    title: 'A sound',
    artist: 'Pine',
    album: '-',
    file: 'Pine - A sound.mp3',
    duration: 87.5102,
  },
  {
    id: 8,
    title: 'A-morphed city dweller',
    artist: 'Pine',
    album: '-',
    file: 'Pine - A-morphed city dweller.mp3',
    duration: 41.247325,
  },
  {
    id: 9,
    title: 'Alko rave (demo)',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Alko rave (demo).mp3',
    duration: 65.59345,
  },
  {
    id: 10,
    title: 'Analog Dream',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Analog Dream.mp3',
    duration: 154.749375,
  },
  {
    id: 11,
    title: 'And Hero dies (demo)',
    artist: 'Pine',
    album: '-',
    file: 'Pine - And Hero dies (demo).mp3',
    duration: 86.1257,
  },
  {
    id: 12,
    title: 'Bad day 4 a gud guy (demo4ka)',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Bad day 4 a gud guy (demo4ka).mp3',
    duration: 72.09795,
  },
  {
    id: 13,
    title: 'Bad day 4 a gud guy',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Bad day 4 a gud guy.mp3',
    duration: 135.079175,
    artwork: [
      {
        src: 'f339b67431abfd0e7ede89fda36d2185.jpg',
        description: 'Pine - Bad day 4 a gud guy',
      },
      {
        src: 'depressed-depression.gif',
        description: 'Pine - Bad day 4 a gud guy2',
      },
    ],
  },
  {
    id: 14,
    title: 'Beatin on piano',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Beatin on piano.mp3',
    duration: 288.07835,
  },
  {
    id: 15,
    title: 'Budda Rush',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Budda Rush.mp3',
    duration: 109.79265,
  },
  {
    id: 16,
    title: 'Childhood',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Childhood.mp3',
    duration: 102.321625,
  },
  {
    id: 17,
    title: 'Chillout',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Chillout.mp3',
    duration: 98.74285,
  },
  {
    id: 18,
    title: 'Closed mind',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Closed mind.mp3',
    duration: 243.304475,
  },
  {
    id: 19,
    title: 'Connection to eternity',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Connection to eternity.mp3',
    duration: 149.7861,
  },
  {
    id: 20,
    title: 'Cosmic suffocation',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Cosmic suffocation.mp3',
    duration: 136.071813,
  },
  {
    id: 21,
    title: 'Crawler(dema)',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Crawler(dema).mp3',
    duration: 57.7306,
  },
  {
    id: 22,
    title: 'Cyber',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Cyber.mp3',
    duration: 192,
  },
  {
    id: 23,
    title: 'D68000',
    artist: 'Pine',
    album: '-',
    file: 'Pine - D68000.mp3',
    duration: 96.07835,
  },
  {
    id: 24,
    title: 'Dark moon',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Dark moon.mp3',
    duration: 159.1902,
  },
  {
    id: 25,
    title: 'Darko',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Darko.mp3',
    duration: 161.28,
  },
  {
    id: 26,
    title: 'Dead Space',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Dead Space.mp3',
    duration: 292.8849,
  },
  {
    id: 27,
    title: 'Dead memory',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Dead memory.mp3',
    duration: 168.933875,
  },
  {
    id: 28,
    title: 'Dead west',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Dead west.mp3',
    duration: 169.03835,
  },
  {
    id: 29,
    title: 'Did it',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Did it.mp3',
    duration: 201.3257,
  },
  {
    id: 30,
    title: 'Dream',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Dream.mp3',
    duration: 168.20245,
  },
  {
    id: 31,
    title: 'Evil of time',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Evil of time (demchick).mp3',
    duration: 144.091425,
  },
  {
    id: 32,
    title: 'FSP',
    artist: 'Pine',
    album: '-',
    file: 'Pine - FSP (on MM17).mp3',
    duration: 171.493875,
  },
  {
    id: 33,
    title: 'FUnCKER',
    artist: 'Pine',
    album: '-',
    file: 'Pine - FUnCKER.mp3',
    duration: 131.291425,
  },
  {
    id: 34,
    title: 'Factory Rush',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Factory Rush.mp3',
    duration: 198.24325,
  },
  {
    id: 35,
    title: 'Float',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Float.mp3',
    duration: 173.583675,
  },
  {
    id: 36,
    title: 'Forgive me',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Forgive me.mp3',
    duration: 144.091425,
  },
  {
    id: 37,
    title: 'Green Sea something White and sharp Crags',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Green Sea something White and sharp Crags.mp3',
    duration: 158.4849,
  },
  {
    id: 38,
    title: 'Green feeling',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Green feeling.mp3',
    duration: 192.731425,
  },
  {
    id: 39,
    title: 'Hello',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Hello.mp3',
    duration: 277.4204,
  },
  {
    id: 40,
    title: 'Helper',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Helper.mp3',
    duration: 180.401625,
  },
  {
    id: 41,
    title: 'Henry (pre alph)',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Henry (pre alph).mp3',
    duration: 70.661225,
  },
  {
    id: 42,
    title: 'Holy days',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Holy days.mp3',
    duration: 166.34775,
  },
  {
    id: 43,
    title: 'Hope',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Hope.mp3',
    duration: 156.9959,
  },
  {
    id: 44,
    title: 'In movie',
    artist: 'Pine',
    album: '-',
    file: 'Pine - In movie.mp3',
    duration: 193.93305,
  },
  {
    id: 45,
    title: 'Love v1',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Love v1.mp3',
    duration: 123.506925,
  },
  {
    id: 46,
    title: 'Love v2',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Love v2.mp3',
    duration: 126.928975,
  },
  {
    id: 47,
    title: 'Machine town',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Machine town.mp3',
    duration: 82.834275,
  },
  {
    id: 48,
    title: 'Mad sinister #d',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Mad sinister #d.mp3',
    duration: 234.08325,
  },
  {
    id: 49,
    title: 'Mad sinister 1.2.0',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Mad sinister 1.2.0.mp3',
    duration: 277.968975,
  },
  {
    id: 50,
    title: 'Must roll',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Must roll.mp3',
    duration: 112.509375,
  },
  {
    id: 51,
    title: 'NREST (New Resident Evil Soundtrack)',
    artist: 'Pine',
    album: '-',
    file: 'Pine - NREST (New Resident Evil Soundtrack).mp3',
    duration: 126.066925,
  },
  {
    id: 52,
    title: 'Plays prodigy [UniqueMusic]',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Plays prodigy [UniqueMusic].mp3',
    duration: 162.533875,
  },
  {
    id: 53,
    title: 'Project 2 ext',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Project 2 ext.mp3',
    duration: 229.799175,
  },
  {
    id: 54,
    title: 'Project 2',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Project 2.mp3',
    duration: 229.799175,
  },
  {
    id: 55,
    title: 'Racing',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Racing.mp3',
    duration: 180.08815,
  },
  {
    id: 56,
    title: 'Replicant',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Replicant.mp3',
    duration: 262.81795,
  },
  {
    id: 57,
    title: 'Reptile ext',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Reptile ext.mp3',
    duration: 207.54285,
  },
  {
    id: 58,
    title: 'Reptile',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Reptile.mp3',
    duration: 153.67835,
  },
  {
    id: 59,
    title: 'Return in two ticks',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Return in two ticks.mp3',
    duration: 206.83755,
  },
  {
    id: 60,
    title: 'Sad lounge',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Sad lounge.mp3',
    duration: 106.266063,
  },
  {
    id: 61,
    title: 'Saint smoke',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Saint smoke.mp3',
    duration: 175.568975,
  },
  {
    id: 62,
    title: 'Salvation the movie',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Salvation the movie.mp3',
    duration: 138.7102,
  },
  {
    id: 63,
    title: 'Sanctity v2',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Sanctity v2.mp3',
    duration: 92.368975,
  },
  {
    id: 64,
    title: 'Sanctity',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Sanctity.mp3',
    duration: 103.601625,
  },
  {
    id: 65,
    title: 'Sanctus vacuum',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Sanctus vacuum.mp3',
    duration: 137.012225,
  },
  {
    id: 66,
    title: 'Sandal',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Sandal.mp3',
    duration: 190.066925,
  },
  {
    id: 67,
    title: 'Skater theme',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Skater theme.mp3',
    duration: 121.573875,
  },
  {
    id: 68,
    title: 'Slumber Galaxy [Unique Music]',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Slumber Galaxy [Unique Music].mp3',
    duration: 133.0155,
  },
  {
    id: 69,
    title: 'Something',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Something.mp3',
    duration: 179.905281,
  },
  {
    id: 70,
    title: 'Stand Up (demo)',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Stand Up (demo).mp3',
    duration: 74.344475,
  },
  {
    id: 71,
    title: 'Star',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Star.mp3',
    duration: 118.2302,
  },
  {
    id: 72,
    title: 'Startracker',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Startracker.mp3',
    duration: 171.8857,
  },
  {
    id: 73,
    title: 'Step into my',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Step into my.mp3',
    duration: 170.919175,
  },
  {
    id: 74,
    title: 'Sun&Tea 4 supper',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Sun&Tea 4 supper.mp3',
    duration: 139.2849,
  },
  {
    id: 75,
    title: 'Taktak',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Taktak.mp3',
    duration: 154.88,
  },
  {
    id: 76,
    title: 'That`s not mine',
    artist: 'Pine',
    album: '-',
    file: 'Pine - That`s not mine.mp3',
    duration: 157.51835,
  },

  {
    id: 78,
    title: 'Underwater dreamers',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Underwater dreamers.mp3',
    duration: 169.1951,
  },
  {
    id: 79,
    title: 'Unexpected meetings [Unique Music]',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Unexpected meetings [Unique Music].mp3',
    duration: 192.07835,
  },
  {
    id: 80,
    title: 'Untitled',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Untitled.mp3',
    duration: 234.919175,
  },
  {
    id: 81,
    title: 'Vinny',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Vinny.mp3',
    duration: 230.138775,
  },
  {
    id: 82,
    title: 'VinnyGrett',
    artist: 'Pine',
    album: '-',
    file: 'Pine - VinnyGrett.mp3',
    duration: 236.591,
  },
  {
    id: 83,
    title: 'YES. YES.',
    artist: 'Pine',
    album: '-',
    file: 'Pine - YES. YES..mp3',
    duration: 75.6506,
  },
  {
    id: 84,
    title: 'Yu',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Yu.mp3',
    duration: 171.52,
  },
  {
    id: 85,
    title: 'Zombie town',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Zombie town.mp3',
    duration: 158.4849,
  },
  {
    id: 86,
    title: 'astrobell',
    artist: 'Pine',
    album: '-',
    file: 'Pine - astrobell.mp3',
    duration: 130.63835,
  },
  {
    id: 87,
    title: 'chasing UFO',
    artist: 'Pine',
    album: '-',
    file: 'Pine - chasing UFO.mp3',
    duration: 181.5249,
  },
  {
    id: 88,
    title: 'copy',
    artist: 'Pine',
    album: '-',
    file: 'Pine - copy.mp3',
    duration: 98.847325,
  },
  {
    id: 89,
    title: 'cosmo included',
    artist: 'Pine',
    album: '-',
    file: 'Pine - cosmo included.mp3',
    duration: 96.2351,
  },
  {
    id: 90,
    title: 'cube in space',
    artist: 'Pine',
    album: '-',
    file: 'Pine - cube in space.mp3',
    duration: 137.221225,
  },
  {
    id: 91,
    title: 'destiny [Unique Music]',
    artist: 'Pine',
    album: '-',
    file: 'Pine - destiny [Unique Music].mp3',
    duration: 174.62855,
  },
  {
    id: 92,
    title: 'griney',
    artist: 'Pine',
    album: '-',
    file: 'Pine - griney.mp3',
    duration: 108.06855,
  },
  {
    id: 93,
    title: 'higher (piece)',
    artist: 'Pine',
    album: '-',
    file: 'Pine - higher (piece).mp3',
    duration: 20.8457,
  },
  {
    id: 94,
    title: 'mana',
    artist: 'Pine',
    album: '-',
    file: 'Pine - mana.mp3',
    duration: 165.328975,
  },
  {
    id: 95,
    title: 'mash2',
    artist: 'Pine',
    album: '-',
    file: 'Pine - mash2.mp3',
    duration: 150.9355,
  },
  {
    id: 96,
    title: 'of course you can',
    artist: 'Pine',
    album: '-',
    file: 'Pine - of course you can.mp3',
    duration: 244.42775,
  },
  {
    id: 97,
    title: 'psichologist',
    artist: 'Pine',
    album: '-',
    file: 'Pine - psichologist.mp3',
    duration: 146.23345,
  },
  {
    id: 98,
    title: 'reachable (demo)',
    artist: 'Pine',
    album: '-',
    file: 'Pine - reachable (demo).mp3',
    duration: 103.471,
  },
  {
    id: 99,
    title: 'red skyline',
    artist: 'Pine',
    album: '-',
    file: 'Pine - red skyline.mp3',
    duration: 135.3404,
  },
  {
    id: 100,
    title: 'shit',
    artist: 'Pine',
    album: '-',
    file: 'Pine - shit.mp3',
    duration: 125.28325,
  },
  {
    id: 101,
    title: 'shit2',
    artist: 'Pine',
    album: '-',
    file: 'Pine - shit2.mp3',
    duration: 118.2302,
  },
  {
    id: 102,
    title: 'sleep sugar',
    artist: 'Pine',
    album: '-',
    file: 'Pine - sleep sugar.mp3',
    duration: 106.76245,
  },
  {
    id: 103,
    title: 'viv demo',
    artist: 'Pine',
    album: '-',
    file: 'Pine - viv demo.mp3',
    duration: 147.774675,
  },
  {
    id: 104,
    title: 'Без названия',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Без названия.mp3',
    duration: 94.56325,
  },
  {
    id: 105,
    title: 'Ланга',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Ланга.mp3',
    duration: 167.41875,
  },
  {
    id: 106,
    title: 'Нечто куцое и жестокое',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Нечто куцое и жестокое.mp3',
    duration: 221.596725,
  },
  {
    id: 107,
    title: 'придумайте сами',
    artist: 'Pine',
    album: '-',
    file: 'Pine - придумайте сами.mp3',
    duration: 134.661225,
  },
  {
    id: 108,
    title: 'Cosmo included 2',
    artist: 'Pinee',
    album: '-',
    file: 'Pinee - Cosmo included 2.mp3',
    duration: 144.0653,
  },
  {
    id: 109,
    title: 'Untitled',
    artist: 'Unknown',
    album: '-',
    file: 'Unknown - Untitled.mp3',
    duration: 60.081625,
  },
  {
    id: 110,
    title: 'Phase 1, the silence',
    artist: 'pINE',
    album: '-',
    file: 'pINE - Phase 1, the silence.mp3',
    duration: 268.617125,
  },
  {
    id: 111,
    title: 'Bez paleva',
    artist: 'Зшту',
    album: '-',
    file: 'Зшту - Bez paleva.mp3',
    duration: 170.76245,
  },
  {
    id: 112,
    title: 'Без названия',
    artist: 'Неизвестен',
    album: '-',
    file: 'Неизвестен - Без названия.mp3',
    duration: 99.3959,
  },
  {
    id: 113,
    title: 'штормоотрол',
    artist: 'мумий тролль',
    album: '-',
    file: 'мумий тролль - штормоотрол (Pine).mp3',
    duration: 110.863675,
  },
  {
    id: 114,
    title: 'сходят с ума',
    artist: 'так',
    album: '-',
    file: 'так - сходят с ума.mp3',
    duration: 171.493875,
  },
  {
    id: 115,
    title: 'Black sheep',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Black sheep.mp3',
    duration: 134.504475,
    artwork: [
      {
        src: '-50014318_367687538.jpg',
        description: 'Black sheep',
      },
    ],
  },
  {
    id: 116,
    title: 'Deftone',
    artist: 'Pine',
    album: '-',
    file: 'Pine - Deftone.mp3',
    duration: 274.364075,
  },
];

/*

*/
export interface Album {
  id: number;
  title: string;
  tracks: number[];
  description: string;
  cover: string;
}
export const albums: Album[] = [
  {
    id: 0,
    title: 'All tracks',
    tracks: playlist.map(track => track.id),
    description: 'All tracks',
    cover: '/images/covers/all_tracks_cover.jpg',
  },
  {
    id: 1,
    title: 'Funny',
    tracks: [83],
    description: 'Funny tracks',
    cover: '/images/covers/No-Image-Placeholder.svg.png',
  },
  {
    id: 2,
    title: 'Sad',
    tracks: [],
    description: 'Sad tracks',
    cover: '/images/covers/No-Image-Placeholder.svg.png',
  },
  {
    id: 3,
    title: 'Special ocasions',
    tracks: [74, 94, 114],
    description: 'Special ocasions tracks',
    cover: '/images/covers/No-Image-Placeholder.svg.png',
  },
  {
    id: 4,
    title: 'Groovy',
    description: 'Groovy tracks',
    tracks: [75],
    cover: '/images/covers/No-Image-Placeholder.svg.png',
  },
  {
    id: 5,
    title: 'Golden collection',
    description: 'Golden collection tracks',
    tracks: [76],
    cover: '/images/covers/No-Image-Placeholder.svg.png',
  },
  {
    id: 6,
    title: 'Essences',
    description: 'Essences tracks',
    tracks: [63, 50, 115, 15, 66, 27, 89, 102, 10, 13, 75, 48, 116, 26],
    cover: '/images/covers/essences.jpg',
  },
];
